- hosts: localhost

  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

  pre_tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts

    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: result
      tags:
        - debug
        - always

    - name: Set the env var
      set_fact:
        username: "{{ result.stdout }}"
      tags:
        - debug
        - always

    - name: update repositories
      become: true
      pacman:
        update_cache: yes

  tasks:
    - include: tasks/debug.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/pacman-packages.yml
    - include: tasks/brew.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
