- name: Install nodejs and npm
  become: true
  pacman:
    name: ["nodejs", "npm"]
  when: ansible_facts['distribution'] == "Archlinux"
  tags:
    - install
    - node

- name: Install N
  become_user: "{{ lookup('vars', 'username') }}"
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  become_user: "{{ lookup('vars', 'username') }}"
  command: "{{ lookup('env', 'HOME') }}/.config/n/bin/n 15"
  tags:
    - install
    - node
