- name: Install Yarn
  npm:
    name: 'yarn'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install Typescript server
  npm:
    name: 'typescript-language-server'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install Typescript
  npm:
    name: 'typescript'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install TS-Node
  npm:
    name: 'ts-node'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install gridsome
  npm:
    name: '@gridsome/cli'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install yaml language server
  npm:
    name: 'yaml-language-server'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install vimscript language server
  npm:
    name: 'vim-language-server'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install bash language server
  npm:
    name: 'bash-language-server'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install html language server
  npm:
    name: 'vscode-langservers-extracted'
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install graphql language server
  npm:
    name: 'graphql-language-service-cli'
    global: yes
  tags:
    - install
    - node
    - npm
