- name: Install System Packages
  pacman: name={{item}}
  with_items:
    - fwupd
    - dunst
    - acpi
    - i3-gaps
    - exa
    - bat
    - lua
    - luarocks
    - fzf
    - ack
    - adobe-source-han-sans-jp-fonts
    - aegisub
    - alacritty
    - arandr
    - baobab
    - bleachbit
    - blueman
    - brightnessctl
    - chromium
    - code
    - dbeaver
    - discord
    - docker
    - docker-compose
    - fcitx-configtool
    - fcitx-mozc
    - fcitx-qt5
    - feh
    - ffmpeg
    - ffmpegthumbnailer
    - filezilla
    - firefox
    - firefox-developer-edition
    - flameshot
    - gimp
    - gparted
    - htop
    - jq
    - kdenlive
    - libreoffice-fresh
    - lxappearance
    - mkvtoolnix-gui
    - mpd
    - nautilus
    - ncmpcpp
    - neofetch
    - neovim
    - newsboat
    - obs-studio
    - pavucontrol
    - pulseaudio-bluetooth
    - pulsemixer
    - ranger
    - rclone
    - redshift
    - remmina
    - signal-desktop
    - sox
    - sxhkd
    - thunderbird
    - tlp
    - tmux
    - tree
    - udiskie
    - vagrant
    - youtube-dl
    - zathura
    - zathura-pdf-mupdf
  tags:
    - install
    - pacman
    - linux
