- name: Get pacman package list
  when: ansible_facts['distribution'] == "Archlinux"
  command:
    cmd: cat ./packages/pacman.txt
  register: pacman_packages
  tags:
    - install
    - pacman
    - linux

- name: Install System Packages
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  pacman: name={{item}}
  with_items: "{{ pacman_packages.stdout_lines }}"
  tags:
    - install
    - pacman
    - linux
