- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    decrypt: yes
    mode: 0600
    owner: danny
    group: danny
  tags:
    - dotfiles
    - install
    - ssh
