- name: Install ZSH
  become: true
  pacman: name=zsh
  tags:
    - install
    - dotfiles
    - zsh
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - install
    - dotfiles
    - zsh
